---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - webgame.webgame.tech
  resources:
  - webgames
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webgame.webgame.tech
  resources:
  - webgames/finalizers
  verbs:
  - update
- apiGroups:
  - webgame.webgame.tech
  resources:
  - webgames/status
  verbs:
  - get
  - patch
  - update
